Add :seed:run gradle task
bisq-network/bisq2 pull request #102
Opened 2022-02-17 12:11 UTC by alkum

Add support for and document usage of :seed:run task.

2022-02-17 14:51 UTC, chimp1984 requested changes

2022-02-17 14:51 UTC, chimp1984 commented on docs/sample-run-configs.md
> +./gradlew seed:run \
Maybe its better to either limit supportedTransportTypes to clearnet as tor and i2p require local manual setup for the local seed addresses.
Once we use protobuf for serialisation we can start those seeds on a server so its easier to run but currently with java serialisation it carries a slight security risk.

2022-02-17 14:51 UTC, chimp1984 commented on docs/sample-run-configs.md
> +./gradlew seed:run \
So I would recommend to remove 
```
-Dbisq.networkServiceConfig.supportedTransportTypes.0=TOR \
-Dbisq.networkServiceConfig.supportedTransportTypes.1=I2P \
```

2022-02-17 14:51 UTC, chimp1984 commented on docs/sample-run-configs.md
> +./gradlew seed:run \
Actually not sure if typesafe works with `supportedTransportTypes.2=CLEAR` alone or if index need to be 0 in that case. Propably more clear with 0.

2022-02-18 12:09 UTC, alkum commented on docs/sample-run-configs.md
> +./gradlew seed:run \
Yes good point, I removed tor and i2p, kept only the args for clearnet.

2022-02-18 14:48 UTC, merged