fix rename bug on WinOS
bisq-network/bisq2 pull request #107
Opened 2022-02-20 20:25 UTC by salokiam

fix for WinOS, renaming a file must be after closing that file.

2022-02-21 01:12 UTC, chimp1984 requested changes

2022-02-21 01:12 UTC, chimp1984 commented on persistence/src/main/java/bisq/persistence/Persistence.java
> +                }// need to end the catch here to have the temp file autoclose
I assume the tempFile gets closed because its used in `new FileOutputStream(tempFile)`. Maybe we should make it more explicit, for instance to close it in a finally clause or add a bit more info to the comment.

2022-02-21 01:12 UTC, chimp1984 commented on persistence/src/main/java/bisq/persistence/Persistence.java
> +                }// need to end the catch here to have the temp file autoclose
Just checked the code in Bisq (1) at PersistenceManager.
```
// Close resources before replacing file with temp file because otherwise it causes problems on windows
// when rename temp file
fileOutputStream.close();
```

2022-02-21 08:30 UTC, salokiam commented on persistence/src/main/java/bisq/persistence/Persistence.java
> +                }// need to end the catch here to have the temp file autoclose
hmm, yes. Usually a good idea to use try-resource, but in this case it does make the code less readable.
I think its better handled in busq1 I will change it.

2022-02-22 00:35 UTC, chimp1984 commented on persistence/src/main/java/bisq/persistence/Persistence.java
> +                }// need to end the catch here to have the temp file autoclose
Yes, agree.

2022-02-22 00:36 UTC, chimp1984 approved these changes
utACK

2022-02-22 00:37 UTC, merged