Fixing truncating button text issue
bisq-network/bisq2 pull request #1313
Opened 2023-10-31 11:58 UTC by aspire2dev

Created a new css element to pad the buttons that are truncating differently from the other buttons without changing their aspect when in a larger size view and some other adjustments

bisq-network#1246

2023-10-31 14:02 UTC, HenrikJannsen requested changes
NACK

2023-10-31 14:02 UTC, HenrikJannsen commented on desktop/src/main/java/bisq/desktop/main/content/user/bonded_roles/nodes/tabs/registration/NodeRegistrationView.java
> +        importNodeAddressButton.getStyleClass().add("button-reduced-padding");
Better use `addAll`

2023-10-31 14:03 UTC, HenrikJannsen commented
Left button border gets swallowed in min width layout.
Hyperlink should not have line break IMO.

<img width="779" alt="Screenshot 2023-10-31 at 21 02 12" src="https://github.com/bisq-network/bisq2/assets/116298498/4972e09b-c333-4515-9c61-d39e89d4390e">

2023-11-01 15:23 UTC, aspire2dev commented
> Left button border gets swallowed in min width layout. Hyperlink should not have line break IMO.
> <img alt="Screenshot 2023-10-31 at 21 02 12" width="779" src="https://user-images.githubusercontent.com/116298498/279400885-4972e09b-c333-4515-9c61-d39e89d4390e.png">

@HenrikJannsen, this issue is not a regression, as it happens already on main (see image bellow):
![image](https://github.com/bisq-network/bisq2/assets/143408636/decd0095-0485-4269-9fb4-5d4d55add550)

Should it be worked on this issue or can I open another one to review all of the other places where this may be occurring?

2023-11-02 03:57 UTC, HenrikJannsen commented
I would reduce padding and accept ellipsis in "Learn more".
Border issue i only have seen in that screen. I think a 1 or 2 px left padding should fix it.

2023-11-02 20:59 UTC, aspire2dev commented on desktop/src/main/java/bisq/desktop/main/content/user/bonded_roles/nodes/tabs/registration/NodeRegistrationView.java
> +        importNodeAddressButton.getStyleClass().add("button-reduced-padding");
Done

2023-11-02 21:00 UTC, aspire2dev commented
> I would reduce padding and accept ellipsis in "Learn more". Border issue i only have seen in that screen. I think a 1 or 2 px left padding should fix it.

Done

2023-11-03 04:43 UTC, HenrikJannsen approved these changes
utACK

2023-11-03 17:24 UTC, merged