Aspire2dev/fix popups user options
bisq-network/bisq2 pull request #1320
Opened 2023-11-03 15:18 UTC by aspire2dev

The popup windows from the user section (reputation, all buttons) are actually breaking on a too narrow screen.
Merged the Burn BSQ score simulation into the BurnBsqTab2View and moved the controller methods to the BurnBsqTab2Controller. Then added a GridPane to distribute equally the available space on the view independent of the size.

Tried making the popup resize when the underlying window is changed in size, but even binding the prefWidthView that's not working.

Popup size is calculated during runtime depending on size of the window.

2023-11-03 15:19 UTC, aspire2dev commented
@HenrikJannsen, this is a first shot at the changes on the popups from the Reputation view of Users. Please let me know if I can proceed with the same fixes for the score calculation of the BSQ Bonds, Account Age and Signed account age witness.

2023-11-05 06:30 UTC, HenrikJannsen approved these changes
NACK

2023-11-05 06:33 UTC, HenrikJannsen commented
Several layout bugs (did not review in depth) but those have been obvious at a 5 second check. Please test better yourself in future, it takes too much effort for review when it goes often back and forth and there are obvious and easy to spot issues! Some issues might have been before already but if your task is to fix that area it included to fix all past bugs.

<img width="962" alt="Screenshot 2023-11-05 at 13 29 13" src="https://github.com/bisq-network/bisq2/assets/116298498/97c3fdc4-ceef-47f0-b0bc-ff3a309b442d">
<img width="959" alt="Screenshot 2023-11-05 at 13 29 24" src="https://github.com/bisq-network/bisq2/assets/116298498/e995c677-7d5c-412b-9d95-141759c87829">
<img width="809" alt="Screenshot 2023-11-05 at 13 29 52" src="https://github.com/bisq-network/bisq2/assets/116298498/71948bce-be37-4d31-85da-51b35deb23f6">

2023-11-06 22:26 UTC, aspire2dev commented
> 
> Wrong top padding at sub headline: <img alt="Screenshot 2023-11-05 at 13 29 13" width="962" src="https://user-images.githubusercontent.com/116298498/280510148-97c3fdc4-ceef-47f0-b0bc-ff3a309b442d.png">
>
Sorry, the intention here was to demonstrate the POC regarding the utilization of the GridPane and the changes to the code. Next time I'll make sure to also properly format the screen for POCs as well.
>
> Too much space between text and input controls: <img alt="Screenshot 2023-11-05 at 13 29 24" width="959" src="https://user-images.githubusercontent.com/116298498/280510150-e995c677-7d5c-412b-9d95-141759c87829.png">
> 
I'll remove the space, but I didn't change anything on this view.
>
> Space at linebreak: <img alt="Screenshot 2023-11-05 at 13 29 52" width="809" src="https://user-images.githubusercontent.com/116298498/280510153-71948bce-be37-4d31-85da-51b35deb23f6.png">
>
Do you mean the space before the text " Enter the amount of BSQ ..."?

2023-11-07 08:27 UTC, HenrikJannsen commented
> Do you mean the space before the text " Enter the amount of BSQ ..."?

Yes.

2023-11-07 08:27 UTC, HenrikJannsen commented
If its POC it should not be a PR but a draft.

2023-11-07 11:20 UTC, aspire2dev commented
When switching the implementation from Label to Text + Text Flow there are slight differences in the way the text is rendered. As an example, bellow is a screenshot taken from main:

And bellow a screenshot taken replacing Label by Text + TextFlow (instead of using wrap on the Label, I exchanged the implementation to TextFlow)
![image](https://github.com/bisq-network/bisq2/assets/143408636/1405625c-9cd8-4d80-9c37-c3e3d8bd0f00)

Notice how there's a difference in the position of the next button, this is due to the text from the "What is the recommended amount to burn" text section. Is that acceptable or it should be pixel perfect to what it was before?

2023-11-07 11:52 UTC, aspire2dev commented
> > Do you mean the space before the text " Enter the amount of BSQ ..."?
> 
> Yes.
Here I added a #4 item:
![image](https://github.com/bisq-network/bisq2/assets/143408636/b1b7d91c-8841-4675-b971-e397048bc7f1)

Here I just adjusted the spaces:
![image](https://github.com/bisq-network/bisq2/assets/143408636/c0c6ad12-672a-4865-a6c7-0d2f93f6569e)

Which one should I use?

2023-11-07 12:44 UTC, aspire2dev commented
Here a video of the actual implementation of the Burning BSQ view.. Notice that when the window is narrower, both WHY and SCORE tabs get some scrolling. Should I reduce the spacing here (which will affect looks elsewhere) or keep it as is?


https://github.com/bisq-network/bisq2/assets/143408636/84cf03eb-9175-457d-b0dd-a426e14532c2

2023-11-08 18:03 UTC, HenrikJannsen commented
> Notice how there's a difference in the position of the next button, this is due to the text from the "What is the recommended amount to burn" text section. Is that acceptable or it should be pixel perfect to what it was before?

I cannot see any difference. So looks good to me.

2023-11-08 18:04 UTC, HenrikJannsen commented
> Which one should I use?

The one with 6 items.

2023-11-08 18:06 UTC, HenrikJannsen commented
> Here a video of the actual implementation of the Burning BSQ view.. Notice that when the window is narrower, both WHY and SCORE tabs get some scrolling. Should I reduce the spacing here (which will affect looks elsewhere) or keep it as is? If possible, reducing the blank space on left and right would be the best solution. Other views also scroll when in a narrower view, and in some cases, hide the continue button.
> view_gridpane_resize-2023-11-07_08.38.43.mp4

Yes the left and right space should be reduced to maybe 20 px in small width case.

2023-11-10 00:19 UTC, aspire2dev commented
> > Here a video of the actual implementation of the Burning BSQ view.. Notice that when the window is narrower, both WHY and SCORE tabs get some scrolling. Should I reduce the spacing here (which will affect looks elsewhere) or keep it as is? If possible, reducing the blank space on left and right would be the best solution. Other views also scroll when in a narrower view, and in some cases, hide the continue button.
> > view_gridpane_resize-2023-11-07_08.38.43.mp4
> 
> Yes the left and right space should be reduced to maybe 20 px in small width case.

On my submitted solution I did test all narrower sizes I could and did reduce as much as needed to get a comfortable view. If I only left 20 pixels it would not look very nice. Let me know if it should be only 20 px.

Just a reminder, for the view size to change according to the window size, the view has to be opened after the window resizing. For some reason I was not able to figure out, binding is not working to this views.

2023-11-10 01:03 UTC, HenrikJannsen requested changes
NACK

2023-11-10 01:04 UTC, HenrikJannsen commented
Scrollbar not displayed at that window height. It gets displayed when smaller height.
Please squash all the commits with the same commit message.

<img width="1068" alt="Screenshot 2023-11-10 at 08 01 48" src="https://github.com/bisq-network/bisq2/assets/116298498/3062e5bd-c2cb-474b-8a8d-567857753b4c">

2023-11-11 21:32 UTC, aspire2dev commented
> Scrollbar not displayed at that window height. It gets displayed when smaller height. Please squash all the commits with the same commit message.
> <img alt="Screenshot 2023-11-10 at 08 01 48" width="1068" src="https://user-images.githubusercontent.com/116298498/281922510-3062e5bd-c2cb-474b-8a8d-567857753b4c.png">

I tested the possible dimensions and space left over for the width and the height. Then I took the minimum margins that would not trigger scrolling on the view. This was then applied whenever the screen is narrower than either 1100 width or 880 height. So, this way, we don' t have to worry about scrolling in these views.
Also squashed the commits.

2023-11-15 08:44 UTC, HenrikJannsen approved these changes
ACK

2023-11-15 08:47 UTC, HenrikJannsen commented on desktop/src/main/java/bisq/desktop/main/content/user/reputation/accountAge/AccountAgeView.java
> +        root.prefWidthProperty().bind(window.widthProperty().subtract(prefWidth));
Binding have to be in onViewAttached and unbind called in onViewDetached

2023-11-21 11:56 UTC, closed without merging

2023-11-21 11:57 UTC, aspire2dev commented
As my PRs are not up to the standard required and take too much time to review, I'm dropping off the project. Sorry for all the inconvenience...