Elementsd: Unlock and lock wallet between RPC calls
bisq-network/bisq2 pull request #387
Opened 2022-06-14 07:35 UTC by alvasw

2022-06-19 21:23 UTC, chimp1984 requested changes

2022-06-19 21:23 UTC, chimp1984 commented on desktop/src/main/java/bisq/desktop/primary/main/content/wallet/send/WalletSendView.java
> +        passphraseTextField.textProperty().bindBidirectional(model.passphraseProperty());
The bindings and event handlers should be set in the onViewAttached

2022-06-21 02:42 UTC, alvasw commented on desktop/src/main/java/bisq/desktop/primary/main/content/wallet/send/WalletSendView.java
> +        passphraseTextField.textProperty().bindBidirectional(model.passphraseProperty());
Oops, I didn't rebase it correctly.

2022-06-21 07:59 UTC, chimp1984 approved these changes
utACK

2022-06-21 07:59 UTC, merged